# Generated by Django 4.2 on 2024-11-12 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(error_messages={'unique': 'A user with this mobile number already exists .'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', message='enter a valid mobile number')], verbose_name='phone number'),
        ),
    ]
