# Generated by Django 4.2 on 2024-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendor_driver_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
