# Generated by Django 4.2 on 2025-01-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_driver_first_name_driver_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
