# Generated by Django 4.2 on 2025-01-04 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_address', models.TextField(max_length=300, null=True)),
                ('store_phone', models.CharField(max_length=15)),
                ('store_name', models.CharField(max_length=40, null=True)),
                ('business_license', models.FileField(upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('id_number', models.IntegerField(null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
